/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VIcon: typeof import('./components/VIcon.vue')['default']
    VLogo: typeof import('./components/VLogo.vue')['default']
    VMenu: typeof import('./components/VMenu.vue')['default']
    VNavigationBar: typeof import('./components/VNavigationBar.vue')['default']
    VPlanCard: typeof import('./components/VPlanCard.vue')['default']
    VSpacer: typeof import('./components/VSpacer.vue')['default']
    VTechCard: typeof import('./components/VTechCard.vue')['default']
    VTechCarousel: typeof import('./components/VTechCarousel.vue')['default']
  }
}
